### Create user ###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Leanne Graham",
    "email": "Sincere@april.biz",
    "password": "123456"
}

### Login user ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "Sincere@april.biz",
    "password": "123456"
}

### Get routes ###
GET http://localhost:3000/news?theme=technology
